module.exports = {
    // please enter your mysql local username and its password below
    yourLocalMySQLUsername: 'root2',
    yourLocalMySQLPassword: '1234',
    // host: 'localhost',
    // host: 'us-cdbr-east-02.cleardb.com',
    host: process.env.CLEARDB_HOST || 'localhost',
    port: 3306,
    // user: 'poolmanager',
    // user: 'beeed1080b1478',
    user: process.env.CLEARDB_USER || 'poolmanager',
    // password: '1234',
    // password: '970eb798',
    password: process.env.CLEARDB_PASSWORD || '1234',
    // database: 'pooldb',
    // database: 'heroku_4f16e67a2709b1d',
    database: process.env.CLEARDB_DATABASE || 'pooldb',
    tablename: 'pooltable',
    connectionLimit: 100,
}